config/routes.rb
Rails.application.routes.draw do
  resources :trajetos 
  resources :admins do
    collection do
      get 'autocomplete_admin_nome'
    end
  end
  resources :campus_uffs do
    collection do
      get 'autocomplete_admin_nome'
    end
  end
  get 'autocomplete_identificacao_login_nome', to: 'admins#autocomplete_identificacao_login_nome'
  get 'welcome/index'
  get 'search', to: 'search#trajetos'
  get 'search/campus', to: 'search#campus'
  get 'search/iduff', to: 'search#iduff'
  get 'admins/ativar/:id', to: 'admins#ativar', as: :ativar_admin
  get 'admins/desativar/:id', to: 'admins#desativar', as: :desativar_admin
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'trajetos#index'


end

app/views/admins/_form.html.erb
<div class="panel-body">
  <div class="row">
    <div class="col-lg-12">

<%= form_with(model: admin, local: true) do |form| %>
  <% if admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
      <% admin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :nome %>
    <%= form.autocomplete_field :nome, autocomplete_identificacao_login_nome_path, :id_element => '#admin_dados_identificacoes_id', class:"form-control", placeholder:"Digite um Nome ou CPF" %>
  </div>

  <div class="form-group">
    <%= form.hidden_field :dados_identificacoes_id %>
  </div> 

  <%= form.hidden_field :data_desativacao, :value => Time.now %>

  <button type="submit" class="btn btn-default">Salvar</button>

<% end %>

    </div>
  </div>
</div>

app/views/admins/edit.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">Editando</h1>
  </div>
</div>

<div class="row">
  <div class="col-lg-9">
    <div class="panel panel-default">
      <div class="panel-heading">
        Editando Administrador
      </div>

        <%= render 'form', admin: @admin %>

    </div>
  </div>
</div>

<%= link_to 'Voltar', admins_path, class:"btn btn-primary" %> 

app/views/admins/index.html.erb
<% flash.each do |msg| %>
  <div class="alert alert-success" role="alert">
    <p id="notice"><%= notice %></p>
  </div>
<% end %>

<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">Administradores</h1>
  </div>
</div>

<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Ativo</th>
      <th>Identificacao Login</th>
      <th>Data desativação</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admins.each do |admin| %>
      <tr>
        <td><%= admin.nome %></td>
        <td><%= admin.ativo %></td>
        <td><%= admin.dados_identificacoes_id %></td>
        <td><%= admin.data_desativacao %></td>
        <td><%= link_to 'Show', admin %></td>
        <td><%= link_to 'Edit', edit_admin_path(admin) %></td>
        <% if admin.ativo? %>
          <td><%= link_to 'Desativar', desativar_admin_path(admin) %></td>
        <% else %>
          <td><%= link_to 'Ativar', ativar_admin_path(admin) %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin', new_admin_path, class: "btn btn-primary btn-lg" %>

app/views/admins/new.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">Novo Administrador</h1>
  </div>
</div>

<div class="row">
  <div class="col-lg-9">
    <div class="panel panel-default">
      <div class="panel-heading">
        Cadastrando Administrador
      </div>

        <%= render 'form', admin: @admin %>

    </div>
  </div>
</div>

<%= link_to 'Voltar', admins_path, class:"btn btn-primary" %> 

app/views/admins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @admin.nome %>
</p>

<p>
  <strong>Ativo:</strong>
  <%= @admin.ativo %>
</p>

<p>
  <strong>Dados identificacoes:</strong>
  <%= @admin.dados_identificacoes_id %>
</p>

<%= link_to 'Edit', edit_admin_path(@admin) %> |
<%= link_to 'Back', admins_path %>