config/routes.rb
Rails.application.routes.draw do
  resources :trajetos 
  resources :admins do
    collection do
      get 'autocomplete_admin_nome'
    end
  end
  resources :campus_uffs do
    collection do
      get 'autocomplete_admin_nome'
    end
  end
  get 'autocomplete_identificacao_login_nome', to: 'admins#autocomplete_identificacao_login_nome'
  get 'welcome/index'
  get 'search', to: 'search#trajetos'
  get 'search/campus', to: 'search#campus'
  get 'search/iduff', to: 'search#iduff'
  get 'admins/ativar/:id', to: 'admins#ativar', as: :ativar_admin
  get 'admins/desativar/:id', to: 'admins#desativar', as: :desativar_admin
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'trajetos#index'


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<h1>Pagina principal</h1>

<p>Current User: <%= current_user %></p>
<p>Current User.iduff: <%= current_user.iduff %></p>
<h2>Bem Vindo</h2>
<p><%= Pub::IdentificacaoLogin.find_by(iduff: current_user.iduff).nome %></p>
<h2><%= Pub::IdentificacaoLogin.find_by(iduff: current_user.iduff).id %></h2>
<p>Logado: <%= logged_in? %></p>

<p><%= link_to 'Trajetos', trajetos_path %></p> 
<p><%= link_to 'Campus UFF', campus_uffs_path %></p> 
<p><%= link_to 'Administradores', admins_path %></p>

<div class="ui-widget">
    <label for="tags">Tags: </label>
    <input id="tags">
</div>


<script>
    $( function() {
        var availableTags = [
            "ActionScript",
            "AppleScript",
            "Asp",
            "BASIC",
            "C",
            "C++",
            "Clojure",
            "COBOL",
            "ColdFusion",
            "Erlang",
            "Fortran",
            "Groovy",
            "Haskell",
            "Java",
            "JavaScript",
            "Lisp",
            "Perl",
            "PHP",
            "Python",
            "Ruby",
            "Scala",
            "Scheme"
        ];
        $( "#tags" ).autocomplete({
            source: availableTags
        });
    } );
</script>

<%= form_with(url: search_iduff_path, local: true, method: :get) do |form| %>
    <div class="input-group custom-search-form">
        <%= form.text_field :term, class:"form-control", placeholder:"Nome iduff"%>
        <span class="input-group-btn">
            <button class="btn btn-default" type="submit">
                <i class="fa fa-search"></i>
            </button>
        </span>
    </div>
<% end %>

<%= form_tag(admins_path, :method => "get", id: "search-form") do %>
<!-- text field tag=action,args,identifier,placeholdertext... -->
  <%= text_field_tag :search, params[:search], class: "search-query", placeholder: "namesearch", type: "search", data: {autocomplete: autocomplete_admins_nome_admins_path} %>  
  <%= submit_tag "Search" %>
<%end%>

<script type="text/javascript" charset="utf-8">
  $('#search').bind('railsAutocomplete.select', function(event, data){
  $('#search-form').submit()
  });
</script>