config/routes.rb
Rails.application.routes.draw do
  resources :trajetos 
  resources :admins do
    collection do
      get 'autocomplete_admin_nome'
    end
  end
  resources :campus_uffs do
    collection do
      get 'autocomplete_admin_nome'
    end
  end
  get 'autocomplete_identificacao_login_nome', to: 'admins#autocomplete_identificacao_login_nome'
  get 'welcome/index'
  get 'search', to: 'search#trajetos'
  get 'search/campus', to: 'search#campus'
  get 'search/iduff', to: 'search#iduff'
  get 'admins/ativar/:id', to: 'admins#ativar', as: :ativar_admin
  get 'admins/desativar/:id', to: 'admins#desativar', as: :desativar_admin
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'trajetos#index'


end

app/models/trajeto.rb
class Trajeto < ApplicationRecord
    has_many :local_intermediarios
    accepts_nested_attributes_for :local_intermediarios, reject_if: :all_blank, allow_destroy: true
end

app/controllers/trajetos_controller.rb
class TrajetosController < ApplicationController
  before_action :set_trajeto, only: [:show, :edit, :update, :destroy]

  # GET /trajetos
  # GET /trajetos.json
  def index
    @trajetos = Trajeto.where(identificacao_login_id: Pub::IdentificacaoLogin.find_by(iduff: current_user.iduff))
  end

  # GET /trajetos/1
  # GET /trajetos/1.json
  def show
  end

  # GET /trajetos/new
  def new
    @trajeto = Trajeto.new
  end

  # GET /trajetos/1/edit
  def edit
    if isOwner(@trajeto)
    else
      respond_to do |format|
        format.html { redirect_to trajetos_url, notice: 'Você não tem permissão para editar essa carona!' }
        format.json { head :no_content }
      end
    end
  end

  # POST /trajetos
  # POST /trajetos.json
  def create
    @trajeto = Trajeto.new(trajeto_params)

    respond_to do |format|
      if @trajeto.save
        format.html { redirect_to @trajeto, notice: 'Trajeto was successfully created.' }
        format.json { render :show, status: :created, location: @trajeto }
      else
        format.html { render :new }
        format.json { render json: @trajeto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trajetos/1
  # PATCH/PUT /trajetos/1.json
  def update
    respond_to do |format|
      if @trajeto.update(trajeto_params)
        format.html { redirect_to @trajeto, notice: 'Trajeto was successfully updated.' }
        format.json { render :show, status: :ok, location: @trajeto }
      else
        format.html { render :edit }
        format.json { render json: @trajeto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trajetos/1
  # DELETE /trajetos/1.json
  def destroy
    respond_to do |format|
      if isOwner(@trajeto)
        @trajeto.destroy
        format.html { redirect_to trajetos_url, notice: 'Trajeto was successfully destroyed.' }
        format.json { head :no_content }
      else 
        format.html { redirect_to trajetos_url, notice: 'Você não tem permissão para excluir essa carona!!' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trajeto
      @trajeto = Trajeto.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def trajeto_params
      params.require(:trajeto).permit(:local_partida, :local_destino, :horario, :passageiros, :valor, :observacao, :identificacao_login_id,
        local_intermediarios_attributes: [:id, :local, :_destroy])
    end

    def isOwner(trajeto)
      trajeto.identificacao_login_id == Pub::IdentificacaoLogin.find_by(iduff: current_user.iduff).id
    end
end

app/helpers/trajetos_helper.rb
module TrajetosHelper
end

app/views/trajetos/_form.html.erb
<div class="panel-body">
  <div class="row">
    <div class="col-lg-12">

<%= form_with(model: trajeto, local: true) do |form| %>
  <% if trajeto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(trajeto.errors.count, "error") %> prohibited this trajeto from being saved:</h2>

      <ul>
      <% trajeto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div id="partida_select" class="form-group" style="display:none">
    <%= form.label :local_partida %>
    <%= form.select(:local_partida, CampusUff.all.map{|c| [c.nome]}, { include_blank: 'Local de Partida' }, class:"form-control" ) %>
  </div> 

  <div id="partida_texto" class="form-group">
    <%= form.label :local_partida %>
    <input class="form-control" type="text" name="trajeto[local_partida]" id="p_texto">
  </div>

  <input id="checkbox" type="checkbox"> Selecionar Campus UFF

  <div id='local_intermediarios' class="fields">
      <%= form.fields_for :local_intermediarios do |local| %>
        <%= render partial: "local_intermediario_fields", locals: { f: local } %>
      <% end %>
      <br>
      <%= link_to_add_association 'Adicionar Local Intermediario', form, :local_intermediarios %>
  </div>
  <br>

  <div id="destino_select" class="form-group" style="display:none">
    <%= form.label :local_destino %>
    <%= form.select(:local_destino, CampusUff.all.map{|c| [c.nome]}, { include_blank: 'Local de Destino' }, class:"form-control" ) %>
  </div>

  <div id="destino_texto" class="form-group">
    <%= form.label :local_destino %>
    <input class="form-control" type="text" name="trajeto[local_destino]" id="d_texto">
  </div>


  <input id="checkbox2" type="checkbox"> Selecionar Campus UFF

  <div class="form-row">
    <div class="form-group col-lg-6">
      <%= form.label :horario, class:"mt-3" %> <br>
      <%= form.datetime_select :horario, {} %>
    </div>

    <div class="form-group col-lg-6">
      <%= form.label :passageiros %>
      <%= form.select :passageiros, (1..5), {}, class:"form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :valor %>
    <%= form.number_field :valor, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :observacao %>
    <%= form.text_area :observacao, class:"form-control" %>
  </div>

  <%= form.hidden_field :identificacao_login_id, :value => Pub::IdentificacaoLogin.find_by(iduff: current_user.iduff).id %>

  <button type="submit" class="btn btn-default">Salvar</button>
<% end %>

    </div>
  </div>
</div>
<%= javascript_tag do %>
  var checkbox = document.getElementById('checkbox');
  var partida_texto = document.getElementById('partida_texto');
  var partida_select = document.getElementById('partida_select');
  var input_partida = document.getElementById('p_texto');
  var input_partida_select = document.getElementById('trajeto_local_partida')

  var checkbox2 = document.getElementById('checkbox2');
  var destino_texto = document.getElementById('destino_texto');
  var destino_select = document.getElementById('destino_select');
  var input_destino = document.getElementById('d_texto');
  var input_destino_select = document.getElementById('trajeto_local_destino')

  checkbox.onchange = function(){
    if(checkbox.checked) {
      partida_texto.style.display = 'none';
      partida_select.style.display = 'block';
      input_partida.name = 'none';
    } else {
      partida_texto.style.display = 'block';
      partida_select.style.display = 'none';
      input_partida.name = 'trajeto[local_partida]';
    }
  }

  checkbox2.onchange = function(){
    if(checkbox2.checked) {
      destino_texto.style.display = 'none';
      destino_select.style.display = 'block';
      input_destino.name = 'nada';
    } else {
      destino_texto.style.display = 'block';
      destino_select.style.display = 'none';
      input_destino.name = 'trajeto[local_destino]';
    }
  }

<% end %>

app/views/trajetos/_local_intermediario_fields.html.erb
<div class="nested-fields">
   <%= f.label :local %> 
   <%= f.text_field :local %>
   
   <%= link_to_remove_association('Remover', f) %>
</div> 

app/views/trajetos/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Editando Carona</h1>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                Carona
                </div>

            <%= render 'form', trajeto: @trajeto %>
            
            </div>
        </div>
    </div>

    <%= link_to 'Voltar', trajetos_path, class:"btn btn-primary" %> 
    <%= link_to 'Show', @trajeto, class:"btn btn-primary" %>
</div>

app/views/trajetos/index.html.erb
<div class="container">

<% flash.each do |msg| %>
  <div class="alert alert-success" role="alert">
    <p id="notice"><%= notice %></p>
  </div>
<% end %>

<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>Local partida</th>
      <th>Local destino</th>
      <th>Horario</th>
      <th>Passageiros</th>
      <th>Valor</th>
      <th>Observacao</th>
      <th>Login id</th>

      <th colspan="3">
      <%= link_to new_trajeto_path, class:"btn btn-success btn-circle" do %>
       <i class="fa fa-plus"></i>
      <% end %>
      </th>
    </tr>
  </thead>

  <tbody>
    <% @trajetos.each do |trajeto| %>
      <tr>
        <td><%= trajeto.local_partida %></td>
        <td><%= trajeto.local_destino %></td>
        <td><%= trajeto.horario %></td>
        <td><%= trajeto.passageiros %></td>
        <td><%= trajeto.valor %></td>
        <td><%= trajeto.observacao %></td>
        <td><%= trajeto.identificacao_login_id %></td>
        <td><%= link_to 'Mostrar', trajeto %></td>
        <td><%= link_to 'Editar', edit_trajeto_path(trajeto) %></td>
        
        <td><%= link_to 'Excluir', trajeto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Adicionar Carona', new_trajeto_path, class: "btn btn-primary btn-lg" %>

</div>

app/views/trajetos/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Nova Carona</h1>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                Carona
                </div>

            <%= render 'form', trajeto: @trajeto %>
            
            </div>
        </div>
    </div>

    <%= link_to 'Voltar', trajetos_path, class:"btn btn-primary" %> 

</div>

app/views/trajetos/show.html.erb
<p id="notice"><%= notice %></p>


<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">
      <span class="label label-info">
        <i class="fa fa-user"></i> <%= @trajeto.passageiros %>
      </span>
        <%= @trajeto.local_partida %> <i class="fa fa-arrow-right"></i> <%= @trajeto.local_destino %>
    </h3>
  </div>
  <div class="panel-body">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Partida: <%= @trajeto.local_partida %>
      </li>
      <% @trajeto.local_intermediarios.each do |local|%>
        <li class="list-group-item">
          Local Intermediario: <%= local.local %>
        </li>
      <% end %>
      <li class="list-group-item">
        Destino: <%= @trajeto.local_destino %>
      </li>
      <li class="list-group-item">
      <i class="fa fa-clock-o"></i> <%= @trajeto.horario %>
      </li>
      <li class="list-group-item">
      <i class="fa fa-user"></i> <%= @trajeto.passageiros %> Passageiros
      </li>
      <li class="list-group-item">
        Observação: <%= @trajeto.observacao %>
      </li>
    <ul>
  </div>
</div>

<%= link_to 'Editar', edit_trajeto_path(@trajeto), class: "btn btn-primary" %> 
    <%= link_to 'Voltar', trajetos_path, class: "btn btn-primary" %>