config/routes.rb
Rails.application.routes.draw do
  resources :trajetos 
  resources :admins do
    collection do
      get 'autocomplete_admin_nome'
    end
  end
  resources :campus_uffs do
    collection do
      get 'autocomplete_admin_nome'
    end
  end
  get 'autocomplete_identificacao_login_nome', to: 'admins#autocomplete_identificacao_login_nome'
  get 'welcome/index'
  get 'search', to: 'search#trajetos'
  get 'search/campus', to: 'search#campus'
  get 'search/iduff', to: 'search#iduff'
  get 'admins/ativar/:id', to: 'admins#ativar', as: :ativar_admin
  get 'admins/desativar/:id', to: 'admins#desativar', as: :desativar_admin
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'trajetos#index'


end

app/views/layouts/admins.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Carona</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application' %>
    <%= stylesheet_link_tag    'admins' %>
    <!-- Bootstrap Core CSS -->
    
  </head>

    <body>

        <div id="wrapper">

            <!-- Navigation -->
            <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <%= link_to 'Carona UFF', root_path, class:"navbar-brand"%>
                </div>
                <!-- /.navbar-header -->

                <ul class="nav navbar-top-links navbar-right">
                    
                    <!-- /.dropdown -->
                    
                    </li>
                    <!-- /.dropdown -->
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                            </li>
                            <li>
                              <%= link_to trajetos_path do %>
                                <i class="fa fa-car fa-fw"></i> Caronas
                              <% end %>
                            </li>
                            <li class="divider"></li>
                            <li><a href="login.html"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                            </li>
                        </ul>
                        <!-- /.dropdown-user -->
                    </li>
                    <!-- /.dropdown -->
                </ul>
                <!-- /.navbar-top-links -->

                <div class="navbar-default sidebar" role="navigation">
                    <div class="sidebar-nav navbar-collapse">
                        <ul class="nav" id="side-menu">
                            <li class="sidebar-search">
                            
                                <!-- /input-group -->
                            </li>
                            <li>
                                <a><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                            </li>
                            <li>
                                <%= link_to admins_path do %>
                                <i class="fa fa-users fa-fw"></i> Administradores
                                <% end %>
                            </li>
                            <li>
                                <%= link_to campus_uffs_path do %>
                                <i class="fa fa-mortar-board fa-fw"></i> Campus UFF
                                <% end %>
                            </li>                   
                        </ul>
                    </div>
                    <!-- /.sidebar-collapse -->
                </div>
                <!-- /.navbar-static-side -->
            </nav>

            <!-- Page Content -->
            <div id="page-wrapper">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-12">
                            
                            <%= yield %>
                        </div>
                        <!-- /.col-lg-12 -->
                    </div>
                    <!-- /.row -->
                </div>
                <!-- /.container-fluid -->
            </div>
            <!-- /#page-wrapper -->

        </div>
        <!-- /#wrapper -->
        <%= javascript_include_tag 'application' %>
        <%= javascript_include_tag 'admins' %>
    </body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Carona</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application' %>
    <%= stylesheet_link_tag    'admins' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag 'admins' %>
  </head>

  <body>
    <div class="container">

      <!-- Static navbar -->
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to 'Carona UFF', root_path, class:"navbar-brand" %>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav"></ul>
            <%= form_with(url: search_path, local: true, method: :get, class:"navbar-form navbar-left") do |form| %>
              <div class="form-group">
                <%= form.text_field :term, class:"form-control", placeholder:"Local de partida"%>
              </div>
              <div class="form-group">
                <%= form.text_field :term2, class:"form-control", placeholder:"Local de destino"%>
              </div>
              <button type="submit" class="btn btn-default">Pesquisar</button>
            <% end %>
            <ul class="nav navbar-nav navbar-right">
              
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= Pub::IdentificacaoLogin.find_by(iduff: current_user.iduff).nome %> <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li>
                      <%= link_to admins_path do %>
                        <i class="fa fa-user fa-fw"></i> Perfil
                      <% end %>
                    </li>
                    
                    <li role="separator" class="divider"></li>
                    <li>
                      <%= link_to root_path do %>
                        <i class="fa fa-sign-out fa-fw"></i> Sair
                      <% end %>
                    </li>
                  </ul>
                </li>
              
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>

      <%= yield %>
    </div> <!-- /container -->
  </body>
</html>